import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Mindfuck</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='main'>
        <div className='center'>
          <h2>what color is written? / what color is the text?</h2>
          <h2>jaká barva je napsaná / jakou barvu má text?</h2>

          <div 
          className='table center'
          style={{
            background: "green"
          }}>
            <h1 
            style={{
              color: "orange",
              fontSize: "70px"
            }}>BLUE</h1>
          </div>
          
          <div className='answers'>
            <button
            className='choiceButton' 
            style={{
              color: "white",
              background: "green"
            }}>ORANGE</button>

            <button
            className='choiceButton' 
            style={{
              color: "transparent",
              background: "blue"
            }}>BLUE</button>

            <button
            className='choiceButton' 
            style={{
              color: "black",
              background: "orange"
            }}>GREEN</button>
          </div>


        </div>
      </main>
    </>
  )
}
